nazvanie_zakaza = input("Название заказа: ")
imya_zakazchika = input("Имя заказчика: ")
nazvanie_pozitsii_1 = input("Название первой позиции: ")
kolichestvo_1 = int(input("Количество первой позиции: "))
tsena_1 = float(input("Цена первой позиции: "))
nazvanie_pozitsii_2 = input("Название второй позиции: ")
kolichestvo_2 = int(input("Количество второй позиции: "))
tsena_2 = float(input("Цена второй позиции: "))
stoimost_dostavki = float(input("Стоимость доставки: "))
vnesennaya_summa = float(input("Внесённая сумма: "))
print(f"Заказ-{nazvanie_zakaza}:")
print(f"Заказчик: {imya_zakazchika}")
print(f"{nazvanie_pozitsii_1}, {kolichestvo_1}, {tsena_1:.2f}, {kolichestvo_1 * tsena_1:.2f}")
print(f"{nazvanie_pozitsii_2}, {kolichestvo_2}, {tsena_2:.2f}, {kolichestvo_2 * tsena_2:.2f}")
print(f"Стоимость товаров: {kolichestvo_1 * tsena_1 + kolichestvo_2 * tsena_2:.2f}")
print(f"Доставка: {stoimost_dostavki:.2f}")
print(f"Общая сумма: {(kolichestvo_1 * tsena_1 + kolichestvo_2 * tsena_2) + stoimost_dostavki:.2f}")
print(f"Общее количество единиц: {kolichestvo_1 + kolichestvo_2}")
print(f"Сдача: {vnesennaya_summa - ((kolichestvo_1 * tsena_1 + kolichestvo_2 * tsena_2) + stoimost_dostavki):.2f}")
